name: mhasql-th
version: 0.5.0
github: mbj/mhasql-th
category: Hasql, Database, PostgreSQL, Template Haskell
synopsis: Template Haskell integration for hasql.
description: Fork of official hasql-th with different type generation trade offs.
author: Markus Schirp <mbj@schirp-dso.com>
maintainer: Markus Schirp <mbj@schirp-dso.com>
copyright: (c) 2023 Markus Schirp, (c) 2015, Nikita Volkov
license: MIT
license-file: LICENSE

default-extensions:
- ApplicativeDo
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- LiberalTypeSynonyms
- MagicHash
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PatternGuards
- ParallelListComp
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- UnboxedTuples

dependencies:
- base
- bytestring
- containers
- contravariant
- foldl
- hasql
- postgresql-syntax
- template-haskell
- template-haskell-compat-v0208
- text
- uuid
- vector

library:
  source-dirs: library
  exposed-modules:
    MHasql.TH
  other-modules:
    MHasql.TH.Construction.Exp
    MHasql.TH.Extraction.ChildExprList
    MHasql.TH.Extraction.Exp
    MHasql.TH.Extraction.InputTypeList
    MHasql.TH.Extraction.OutputTypeList
    MHasql.TH.Extraction.PlaceholderTypeMap
    MHasql.TH.Extraction.PrimitiveType
    MHasql.TH.Prelude
