name: hasql-mth
version: 0.5.0
github: mbj/hasql-mth
category: Hasql, Database, PostgreSQL, Template Haskell
synopsis: Template Haskell integration for hasql.
description: Fork of official hasql-th with different type generation trade offs.
author: Markus Schirp <mbj@schirp-dso.com>
maintainer: Markus Schirp <mbj@schirp-dso.com>
copyright: (c) 2023 Markus Schirp, (c) 2015, Nikita Volkov
license: MIT
license-file: LICENSE

default-extensions:
- FlexibleInstances
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections

dependencies:
- base
- bytestring
- containers
- contravariant
- foldl
- hasql
- postgresql-syntax
- tasty-mgolden
- template-haskell
- template-haskell-compat-v0208
- text
- uuid
- vector

ghc-options:
- -Wall

flags:
  development:
    description: Run GHC with development flags
    default: false
    manual: true

when:
- condition: flag(development)
  then:
    ghc-options:
    - -Werror
    - -fplugin=SourceConstraints
    dependencies:
    - source-constraints
  else:
    ghc-options: -Wwarn

library:
  source-dirs: src
  exposed-modules:
  - Hasql.MTH
  - Hasql.MTH.Codec

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - cbt
    - dbt
    - devtools
    - hasql
    - hasql-mth
    - mio-core
    - mprelude
    - tasty
    - tasty-hunit
    - unliftio
  doctest:
    source-dirs: test/doctest
    main: Main.hs
    dependencies:
    - doctest
    - hasql-mth
